<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-83KADBQ" name="sales_invoice_estimate.Customer_Mobile_new_existingTest" tests="7" failures="0" timestamp="28 Jan 2021 10:48:33 GMT" time="87.995" errors="1">
  <testcase name="registrationTest" time="0.008" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest">
    <error type="org.testng.SkipException" message="Skipping this Test">
      <![CDATA[org.testng.SkipException: Skipping this Test
	at sales_invoice_estimate.Customer_Mobile_new_existingTest.registrationTest(Customer_Mobile_new_existingTest.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- registrationTest -->
  <testcase name="barcode4_2_delete_save" time="14.929" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
  <testcase name="barcode3_enoughstock" time="2.760" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
  <testcase name="barcode4" time="21.795" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
  <testcase name="barcode2" time="16.448" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
  <testcase name="Customer_Mobile_existing_login" time="16.745" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
  <testcase name="barcode1" time="15.310" classname="sales_invoice_estimate.Customer_Mobile_new_existingTest"/>
</testsuite> <!-- sales_invoice_estimate.Customer_Mobile_new_existingTest -->
